import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "../assets/globals.css";
import Header from "@/components/header/header";
import Footer from "@/components/footer/footer";
import { UserProvider } from "@/context/UserContext";
import Sidebar from "@/components/sidebar/sidebar";
import { AuthProvider } from "@/context/AuthContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// For SEO
export const metadata: Metadata = {
  title: "E-Pasal",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-purple-300`}
      >
        <AuthProvider>
         <UserProvider>
            <Header />
            {children}
            <Sidebar />
            <Footer />
          </UserProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
